name: Create Status

on:
  workflow_call:
    inputs:
      name:
        type: string
        description: Name of the status
        required: true
      result:
        type: string
        description: Execution result (success or failure)
        required: true

jobs:
  status_check:
    runs-on: ${{ vars.RUNNER_TERRAFORM }}

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          fetch-depth: 2

      - name: Commit hash
        if: github.event_name == 'push'
        run: |
          echo "SHA=${{ github.sha }}" >> "$GITHUB_ENV"

      - name: Get previous commit SHA if triggered by pull request event
        if: github.event_name == 'pull_request'
        run: |
          # プルリクエストイベントがトリガーされた場合、マージコミットのSHAではなく直前のコミットSHAを取得する
          github_sha=$(git log --pretty=format:"%H" -n 2 | tail -n 1)
          echo "SHA=$github_sha" >> "$GITHUB_ENV"

      - name: Create status
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/statuses/"$SHA" \
            -f state=${{ inputs.result }} \
            -f description="${{ inputs.name }} ${{ inputs.result }}" \
            -f context=${{ inputs.name }}_succeeded
        env:
          GH_TOKEN: ${{ github.token }}
